### ISSUE TITLE
fitsio installed does not work in new anacondas

### ISSUE THREAD

**Issue by esheldon** [mgckind/easyaccess#145]
It can't find libbz2
It is probably related to this issue:

https://github.com/ContinuumIO/anaconda-issues/issues/2441

**Comment by kadrlica** [comment]
From the Anaconda 5.1.0 install with a `conda update --all`
```
conda create -n tmp fitsio --channel mgckind
Solving environment: done

## Package Plan ##

  environment location: /home/s1/kadrlica/software/anaconda/anaconda2-5.1.0/envs/tmp

  added / updated specs:
    - fitsio


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    fitsio-0.9.11              |           py36_1         1.6 MB  mgckind
    python-3.6.5               |       hc3d631a_1        29.4 MB
    ------------------------------------------------------------
                                           Total:        31.0 MB
...

Downloading and Extracting Packages
fitsio 0.9.11############################################################ | 100%
python 3.6.5############################################################# | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate tmp
#
# To deactivate an active environment, use
#
#     $ conda deactivate
$ activate tmp
$ SKIP_BZIP_TEST=true python -c "import fitsio; fitsio.test.test()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/s1/kadrlica/software/anaconda/anaconda2-5.1.0/envs/tmp/lib/python3.6/site-packages/fitsio/__init__.py", line 9, in <module>
    from . import fitslib
  File "/home/s1/kadrlica/software/anaconda/anaconda2-5.1.0/envs/tmp/lib/python3.6/site-packages/fitsio/fitslib.py", line 29, in <module>
    from . import _fitsio_wrap
ImportError: libbz2.so.1.0: cannot open shared object file: No such file or directory
```

**Comment by kadrlica** [comment]
In contrast:

```
conda create -n tmp2 fitsio --channel kadrlica
Solving environment: done

## Package Plan ##

  environment location: /home/s1/kadrlica/software/anaconda/anaconda2-5.1.0/envs/tmp2

  added / updated specs:
    - fitsio


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    fitsio-0.9.12rc1           |           py27_0         1.2 MB  kadrlica

...

Downloading and Extracting Packages
fitsio 0.9.12rc1############################################################################################# | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate tmp2
#
# To deactivate an active environment, use
#
#     $ conda deactivate

$ conda activate tmp2
$ SKIP_BZIP_TEST=true python -c "import fitsio; fitsio.test.test()"
testNonStandardKeyValue (fitsio.test.TestWarnings) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.003s

OK
testAsciiTableWriteRead (fitsio.test.TestReadWrite) ... ok
testBz2Read (fitsio.test.TestReadWrite) ... skipped 'skipping bzip tests'
testChecksum (fitsio.test.TestReadWrite) ... ok
testExtVer (fitsio.test.TestReadWrite) ... ok
testGZIPTileCompressedWriteRead (fitsio.test.TestReadWrite) ... ok
testGZWriteRead (fitsio.test.TestReadWrite) ... ok
testHCompressTileCompressedWriteRead (fitsio.test.TestReadWrite) ... ok
testHeaderContinue (fitsio.test.TestReadWrite) ... ok
testHeaderWriteRead (fitsio.test.TestReadWrite) ... ok
testImageSlice (fitsio.test.TestReadWrite) ... ok
testImageWriteRead (fitsio.test.TestReadWrite) ... ok
testImageWriteReadFromDims (fitsio.test.TestReadWrite) ... ok
testImageWriteReadFromDimsChunks (fitsio.test.TestReadWrite) ... ok
testLowerUpper (fitsio.test.TestReadWrite) ... ok
testMoveByName (fitsio.test.TestReadWrite) ... ok
testPLIOTileCompressedWriteRead (fitsio.test.TestReadWrite) ... ok
testReadRaw (fitsio.test.TestReadWrite) ... ok
testRiceTileCompressedWriteRead (fitsio.test.TestReadWrite) ... ok
testSlice (fitsio.test.TestReadWrite) ... ok
testTableAppend (fitsio.test.TestReadWrite) ... ok
testTableInsertColumn (fitsio.test.TestReadWrite) ... ok
testTableIter (fitsio.test.TestReadWrite) ... ok
testTableSubsets (fitsio.test.TestReadWrite) ... ok
testTableWriteDictOfArrays (fitsio.test.TestReadWrite) ... ok
testTableWriteDictOfArraysScratch (fitsio.test.TestReadWrite) ... ok
testTableWriteDictOfArraysVar (fitsio.test.TestReadWrite) ... ok
testTableWriteListOfArrays (fitsio.test.TestReadWrite) ... ok
testTableWriteListOfArraysScratch (fitsio.test.TestReadWrite) ... ok
testTableWriteListOfArraysVar (fitsio.test.TestReadWrite) ... ok
testTableWriteRead (fitsio.test.TestReadWrite) ... ok
testTrimStrings (fitsio.test.TestReadWrite) ... ok
testVariableLengthColumns (fitsio.test.TestReadWrite) ... ok

----------------------------------------------------------------------
Ran 32 tests in 0.698s

OK (skipped=1)
```

**Comment by kadrlica** [comment]
To summarize above, it looks like the older version of fitsio that I packaged does still come with libbz2, but @mgckind version has the issue that Erin noted.
