### ISSUE TITLE
 Script 'scripts/easyaccess' not found in metadata

### ISSUE THREAD

**Issue by georgezch** [mgckind/easyaccess#153]
Tried to install using conda
```
georgez:~$ easyaccess
Traceback (most recent call last):
  File "/home/georgez/anaconda2/bin/easyaccess", line 4, in <module>
    __import__('pkg_resources').run_script('easyaccess==1.4.3', 'easyaccess')
  File "/home/georgez/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 657, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/georgez/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1428, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/easyaccess' not found in metadata at '/home/georgez/anaconda2/lib/python2.7/site-packages/easyaccess-1.4.3.dist-info'
```

**Comment by kadrlica** [comment]
Thanks @georgezch. For reference, this was using:
```
conda install easyaccess==1.4.3 -c mgckind
```
on Ubuntu.

**Comment by mgckind** [comment]
I have a py2 test conda environment in Ubuntu but can't reproduce the problem,
my guess is that setuptools is not installed (or is old), I'd recommend to install or update conda, then create a new environment (either py2 or py3) and try installing it again.

**Comment by kadrlica** [comment]
The conda install should grab the necessary oracle libraries, right? I think @georgezch has tried an install into a fresh environment and is getting an oracle error.

**Comment by mgckind** [comment]
yes, it should. I'd recommend miniconda3 (and create a env with python2 if needed).

**Comment by georgezch** [comment]
I tried using miniconda3 to create a python2 environment. Now I get the following message:

```
(py27) georgez:~$ easyaccess
Traceback (most recent call last):
  File "/home/georgez/miniconda3/envs/py27/bin/easyaccess", line 4, in <module>
    __import__('pkg_resources').run_script('easyaccess==1.4.3', 'easyaccess')
  File "/home/georgez/miniconda3/envs/py27/lib/python2.7/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/georgez/miniconda3/envs/py27/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/home/georgez/miniconda3/envs/py27/lib/python2.7/site-packages/easyaccess-1.4.3-py2.7.egg/EGG-INFO/scripts/easyaccess", line 2, in <module>
    # EASY-INSTALL-SCRIPT: 'easyaccess==1.4.3','easyaccess'
  File "/home/georgez/miniconda3/envs/py27/lib/python2.7/site-packages/easyaccess-1.4.3-py2.7.egg/easyaccess/__init__.py", line 1, in <module>
  File "/home/georgez/miniconda3/envs/py27/lib/python2.7/site-packages/easyaccess-1.4.3-py2.7.egg/easyaccess/easyaccess.py", line 9, in <module>
  File "build/bdist.linux-x86_64/egg/cx_Oracle.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/cx_Oracle.py", line 6, in __bootstrap__
ImportError: libaio.so.1: cannot open shared object file: No such file or directory
```

**Comment by mgckind** [comment]
You need that extra ubuntu library, use this 
`sudo apt-get install libaio1`
and try again :)

**Comment by georgezch** [comment]
Okay, that was easy to fix! One more thing, now I get the following:
```
georgez:~$ easyaccess

Error in DES_SERVICES config file, creating a new one...
File might not exists or is not configured correctly


Adding section db-dessci to des_service file

Enter username : 
```
After I enter my username it asks for a password. What username/password combination am I supposed to use? I could not make it to work so far.

**Comment by kadrlica** [comment]
The username/password should be the same one you are using to login to confluence.

**Comment by mgckind** [comment]
yes, or send me an email if it doesn't then work.
