### ISSUE TITLE
easyaccess hangs and ctrl-C doesn't work after wrong SQL statement

### ISSUE THREAD

**Issue by bruno-moraes** [mgckind/easyaccess#35]
If the user by mistake tries a wrong SQL statement, an Oracle Database Error is raised. The next command then hangs, even if correct. Ctrl-C doesn't work. The user is forced to kill the whole terminal window and restart. Example below (username edited out by hand): 

```
DESDB ~> find_user <username>

    | ☆            |  Press Ctrl-C to abort    Rows : 1, Avg time (rows/sec): 

1 rows in 0.29 seconds

   USERNAME               EMAIL FIRSTNAME LASTNAME
1  username      username@gmail.com   John  Doe

_________
DESDB ~> find user <username>;

    | ☆            |  Press Ctrl-C to abort 
<class 'cx_Oracle.DatabaseError'>
ORA-00900: invalid SQL statement

_________
DESDB ~> find_user <username>

    |☆             |  Press Ctrl-C to abort Traceback (most recent call last):
  File "/home/brunomor/src/EUPS_DESDM/eups/packages/Linux64/easyaccess/1.1.0+1/bin/easyaccess", line 2029, in <module>
    easy_or(conf, desconf, db, quiet=args.quiet).cmdloop()
  File "/home/brunomor/src/EUPS_DESDM/eups/packages/Linux64/easyaccess/1.1.0+1/bin/easyaccess", line 370, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/home/brunomor/src/EUPS_DESDM/eups/packages/Linux64/easyaccess/1.1.0+1/bin/easyaccess", line 1359, in do_find_user
    self.query_and_print(query, print_time=True)
  File "/home/brunomor/src/EUPS_DESDM/eups/packages/Linux64/easyaccess/1.1.0+1/bin/easyaccess", line 717, in query_and_print
    self.con.cancel()
cx_Oracle.OperationalError: ORA-01041: internal error. hostdef extension doesn't exist

    |          ☆   |  Press Ctrl-C to abort ^C
```

**Comment by mgckind** [comment]
Hi, yes this has been hard to track, but its a network issue during the interpreter . It happens on some firewall configurations, but it doesn't happen when using the python API. So its the way the shell makes remote the connection, that in some networks it closes the oracle connection. I'll try and  solve this by next release,

**Comment by bruno-moraes** [comment]
OK, thanks for the feedback.
