### ISSUE TITLE
fitsio requires glibc v2.14

### ISSUE THREAD

**Issue by kadrlica** [mgckind/easyaccess#99]
The `fitsio v0.9.8` dependency of `easyaccess` appears to have been built with `glibc v2.14`. Scientific Linux 6.7 (Fermilab cluster operating system), only has `glibc v2.12` and I get the following error trying to import fitsio:
```
>>> import fitsio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/s1/kadrlica/.conda/envs/fitsio/lib/python2.7/site-packages/fitsio/__init__.py", line 9, in <module>
    from . import fitslib
  File "/home/s1/kadrlica/.conda/envs/fitsio/lib/python2.7/site-packages/fitsio/fitslib.py", line 29, in <module>
    from . import _fitsio_wrap
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/s1/kadrlica/.conda/envs/fitsio/lib/python2.7/site-packages/fitsio/_fitsio_wrap.so)
```
This issue cannot be solved as easily as a:
```
conda install glibc=2.19 -c asmeurer
```
because conda was built with the older version of `glibc` and installing a newer version leads to errors and seg faults like:
```
/home/s1/kadrlica/.conda/envs/fitsio/bin/.openssl-post-link.sh: line 7: 1460654 Segmentation fault      $PREFIX/bin/.openssl-libcrypto-fix $PREFIX
Error: Error: post-link failed for: openssl-1.0.2j-0 
```

The proposed solution would be to re-build `fitsio` with an older version of `glibc`.

**Comment by kadrlica** [comment]
The `glibc` error was triggering a `fitsio` import error, which in turn was triggering an import error in `easyaccess`. I've built `fitsio` with `gclib v2.12` and this fixes these problems. The conda packages for `fitsio` can be found [here](https://anaconda.org/kadrlica/fitsio).

**Comment by mgckind** [comment]
I'm looking at this right now, we have 2 options:
1) is to build all versions (py 2.6, 2.7, 3.4, 3.5 and 3.6 at least) for linux/os-x using glibc v.2.12 and use that as default,  which might need to be you (then I can copy the packages) as I all glibc versions I have are newer. 
2) Install glibc from source somewhere and build it there
3) Use a recent version of glibc when this happens build fitsio using `pip install` that comes with conda

I'm inclined for 3 but 1 is good too as it might not need to be done to often

**Comment by kadrlica** [comment]
I'm not sure if I understood options 2 & 3. There are several conda distributions of [`glibc`](https://anaconda.org/search?q=glibc), but I've been nervous that they might break other system components (I think I ran into an issue with curl?).

I'm happy to build and test.

**Comment by mgckind** [comment]
But, didn't you say that using conda to install glibc might not wok?

**Comment by kadrlica** [comment]
I didn't have success before, but I think it is the "right" way to do things. We would need to make sure everything was compatible with the same glibc version.
